line-length = 88
select = ["B", "E", "F", "I", "S", "T20", "PGH", "FBT003", "RUF"]
ignore = [
    "E741", "E742", "E743", # do not use names ‘l’, ‘O’, or ‘I’; they are not a problem with a proper font
]
extend-exclude = [".*", "__pycache__", "build", "dist", "venv", "node_modules"]
fixable = ["I001"]
