name: CI

on:
  push:
    branches:
      - main
      - release
  pull_request:

permissions:
  contents: write

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pre-commit run -a
  build:
    name: Build and bundle
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: dist
  publish:
    name: Deploy
    needs: ["build", "formatting"]
    uses: ./.github/workflows/deploy.yml
