name: Deploy

on:
  workflow_call:

permissions:
  contents: write

jobs:
  publish:
    name: Publish to GH pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: dist
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
